nome = input('qual seu nome? ')
print(f'Muito bem vindo {nome} prazer em te conhecer!')
sexo = input('qual seu sexo? ')
nacionalidade = input('qual sua nacionalidade? ')
dia = input('Dia do Nascimento: ')
mes = input('Mês do Nascimento (Ex:Janeiro): ')
ano = input('Ano do Nascimento: ')
print(f'Nome:{nome}. Sexo:{sexo}. Nacionalidade:{nacionalidade}.Você nasceu no dia {dia} do mês de {mes} do ano de {ano}. Correto?')
